export enum Screen {
  Main = 'Main',
  MainDashboard = 'MainDashboard',
  MainCosts = 'MainCosts',
  MainInvoices = 'MainInvoices',
  MainDevMode = 'MainDevMode',
  Dashboard = 'Dashboard',
  Costs = 'Costs',
  CostsList = 'CostsList',
  CostsAdd = 'CostsAdd',
  CostsAdd2 = 'CostsAdd2',
  CostsAddFinish = 'CostsAddFinish',
  CostsView = 'CostsView',
  Invoices = 'Invoices',
  DevMode = 'DevMode',
}
